baseURL = 'https://GITHUB_USERNAME.github.io/REPO_NAME/'
languageCode = 'it'
title = 'Blogghetto - Manga & Anime'
copyright = 'Â© 2024 Blogghetto'

[params]
    description = 'Pensieri e riflessioni su manga e anime.'
    author = 'Blogghetto'
    japanese_style = true
