baseURL = 'https://blogghetto.github.io/Blogghetto/'
languageCode = 'it'
title = 'Oltre il Velo'
copyright = 'Â© 2024 Oltre il Velo'

[params]
    description = 'Pensieri e riflessioni su manga e anime.'
    author = 'Oltre il Velo'
    japanese_style = true
